"""remove pass

Revision ID: 727661d665e7
Revises: 40aaa5901648
Create Date: 2025-03-19 05:24:37.023483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727661d665e7'
down_revision = '40aaa5901648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
